job('First-Maven-Project-Via-DSL') {
    description("First Maven job generated by the DSL on ${new Date()}, the project is a small Maven project hosted on github")
    scm {
        git("https://github.com/Ashish-Abhinav/maven-demo.git", 'master')
    }
    
    steps {
        maven('clean package', 'SetupBuildJob-master/pom.xml')
    }
    
}
